services:
  api-dev:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: dev
    volumes:
      - ./apps/api/src:/app/apps/api/src
      - ./packages:/app/packages
    ports:
      - "3000:3000"

  api-build:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: build
    ports:
      - "3000:3000"
    profiles:
      - build

  front-dev:
    build:
      context: .
      dockerfile: apps/front/Dockerfile
      target: dev
    volumes:
      - ./apps/front/src:/app/apps/front/src
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000

  front-build:
    build:
      context: .
      dockerfile: apps/front/Dockerfile
      target: prod
    ports:
      - "80:80"
    profiles:
      - build
